-- Database Creation
CREATE DATABASE sales_db;

-- Use of created Database
USE sales_db;

-- Table creation in Database
CREATE TABLE Orders_Raw (
    Customer_Name VARCHAR(255),
    Customer_ID VARCHAR(50),
    Row_ID VARCHAR(50),
    Order_Priority VARCHAR(50),
    Discount VARCHAR(50),
    Unit_Price VARCHAR(50),
    Shipping_Cost VARCHAR(50),
    Ship_Mode VARCHAR(100),
    Customer_Segment VARCHAR(100),
    Product_Category VARCHAR(100),
    Product_Sub_Category VARCHAR(100),
    Product_Container VARCHAR(100),
    Product_Name TEXT,
    Product_Base_Margin VARCHAR(50),
    Country VARCHAR(100),
    Region VARCHAR(100),
    State_or_Province VARCHAR(100),
    City VARCHAR(100),
    Postal_Code VARCHAR(50),
    Order_Date VARCHAR(50),
    Ship_Date VARCHAR(50),
    Profit VARCHAR(50),
    Quantity_ordered_new VARCHAR(50),
    Sales VARCHAR(50),
    Order_ID VARCHAR(50)
);
-- Check the folder from which MySQL is allowed to read files
SHOW VARIABLES LIKE 'secure_file_priv';
-- Import data from a CSV file into the Orders_Raw table
LOAD DATA INFILE "C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/SuperStoreUS-2015 1 (8).csv"
-- Specify the destination table
INTO TABLE Orders_Raw
-- Use UTF-8 encoding to correctly read special characters
CHARACTER SET utf8mb4
-- Define the column separator used in the CSV file
FIELDS TERMINATED BY ','
-- Values may be enclosed in double quotes if it is not in "" (e.g., "Ahmedabad")
OPTIONALLY ENCLOSED BY '"'
-- Define how each row ends in the CSV file (Windows format)
LINES TERMINATED BY '\r\n'
-- Skip the first row because it contains column headers
IGNORE 1 ROWS
(
    Customer_Name,
    Customer_ID,
    Row_ID,
    Order_Priority,
    Discount,
    Unit_Price,
    Shipping_Cost,
    Ship_Mode,
    Customer_Segment,
    Product_Category,
    Product_Sub_Category,
    Product_Container,
    Product_Name,
    Product_Base_Margin,
    Country,
    Region,
    State_or_Province,
    City,
    Postal_Code,
    Order_Date,
    Ship_Date,
    Profit,
    Quantity_ordered_new,
    Sales,
    Order_ID,
    @dummy1,
    @dummy2,
    @dummy3
);

-- Beginner Level SQL Questions

-- 1. Display All Records
-- Write a query to display all records from the Orders table.
-- 2. Select Specific Columns
-- Display only the following columns:
-- Customer Name
-- Product Name
-- Sales
-- Profit
-- 3. Filter by State
-- Find all orders placed from California.
-- 4. Negative Profit Orders
-- Display all products where Profit is negative.
-- 5. Discount Based Filtering
-- Find all orders where Discount is greater than 0.20.
-- 6. Sort Data
-- Display all orders sorted by Sales in descending order.
-- 7. Top Selling Orders
-- Display the Top 10 highest sales orders.
-- 8. Unique Customer Segments
-- Find all unique customer segments available in the dataset.
-- 9. Sales Range Filtering
-- Display orders where Sales is between 500 and 2000.
-- 10. Customer Name Pattern
-- Find customers whose names start with 'A'.

select * from Orders_Raw;
select Customer_Name, Product_Name, Sales, Profit from Orders_Raw;
Select * from Orders_Raw where State_or_Province = "California" ;
select * from Orders_Raw where profit<0;
Select * from Orders_Raw where Discount>0.20;
Select * from Orders_Raw order by sales desc;
Select * from Orders_Raw order by sales desc limit 10;
Select distinct(customer_segment) from Orders_Raw;
Select * from Orders_Raw where sales between 500 and 2000 ;
Select * from Orders_Raw where customer_Name like "A%";

-- ntermediate Level SQL Questions

-- 11. Total Sales
-- Find the total sales generated by the company.
-- 12. Average Profit
-- Calculate the average profit of all orders.
-- 13. Maximum Sales
-- Find the highest sales amount.
-- 14. Minimum Profit
-- Find the lowest profit value.
-- 15. Total Number of Orders
-- Count the total number of orders.
-- 16. Sales by Region
-- Find total sales by region.
-- 17. Profit by State
-- Calculate total profit generated by each state.
-- 18. Average Sales by Segment
-- Find the average sales by customer segment.
-- 19. Customer Count by Region
-- Count how many customers belong to each region.
-- 20. Quantity Sold by Category
-- Find the total quantity sold by product category.

select sum(sales) as total_sales from Orders_Raw;
select avg(profit) as Avg_Profit from Orders_Raw;
select max(sales) as max_sales from Orders_Raw;
select min(profit) as min_Profit from Orders_Raw;
select count(Order_Id) from Orders_Raw;
select Region, Sum(sales) as Total_sales from Orders_Raw group by Region;
select State_or_Province, Sum(sales) as Total_sales_State_wise from Orders_Raw group by State_or_Province;
select Customer_Segment, avg(sales) as Avg_sales_by_customer_segment from Orders_Raw group by Customer_Segment;
select Region, count(customer_ID) from Orders_Raw group by Region;
select Product_Category, sum(sales) from Orders_Raw group by Product_Category;

-- Advanced Level SQL Questions

-- 21. High Sales Regions
-- Find regions where total sales are greater than 50,000.
-- 22. High Profit Categories
-- Find product categories where average profit is greater than 100.
-- 23. Monthly Orders
-- Count the total number of orders placed each month.
-- 24. Shipping Delay Analysis
-- Find the difference in days between order date and ship date.
-- 25. Date Filtering
-- Find all orders placed after June 1, 2015.

select region, sum(sales) as total_sales_more_then_50000 from Orders_Raw group by region having	sum(sales)>50000;
select customer_id, sum(sales) as total_sales from Orders_Raw group by customer_id order by total_sales DESC limit 5;
select month(str_to_date(order_date, '%y-%m-%d')) as Order_month, count(*) as total_order from Orders_Raw group by month(str_to_date(order_date, '%y-%m-%d')) order by order_month;



-- JOIN Practice Questions

-- 26. Returned Orders
-- Using the Returns table, find all returned orders.
-- 27. Non-Returned Orders
-- Find all orders that were not returned.
-- 28. Returned Orders by Region
-- Count the number of returned orders by region.





-- Business Scenario Based Questions

-- 29. Top Customers
-- Find the Top 5 customers based on total sales.
-- 30. Most Profitable Category
-- Find which product category generated the highest profit.

select order_id, Order_date, ship_date, date(DAY, order_date, Ship_date) as days_to_ship from Orders_Raw;


